### ISSUE TITLE
Fix typos in user messages

### ISSUE THREAD

**Issue by paulypeter** [Bibo-Joshi/AkaNamen-Bot#107]
I found some typos I'd like to fix in `bot/commands.py` and `bot/cancel_membership.py`.

Also, is upstream still correct in [CONTRIBUTING.rst](https://github.com/Bibo-Joshi/AkaNamen-Bot/blob/master/.github/CONTRIBUTING.rst)?

**Comment by Bibo-Joshi** [comment]
👍 
`upstream` is just used as name when you add this repo as remote to your local git repo - your can change the naming to your liking.

**Comment by Bibo-Joshi** [comment]
ah, yes, that's probably a renmant of when I had this set up on gitlab. thanks for the catch
